<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\InovaGAB.Application\InovaGAB.Application.csproj" />
    <ProjectReference Include="..\InovaGAB.Domain\InovaGAB.Domain.csproj" />
  </ItemGroup>
</Project>
